/**
 * Copyright (c) 2010-2015 Bryan Beck.
 * All rights reserved.
 * 
 * This project is licensed under LGPL v2.1.
 * See jMovieManager-license.txt for details.
 * 
 */
package jMovieManager.swing.gui;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Locale;
import jmm.utils.LocaleManager;
import jmm.utils.OperatingSystem;
import jmm.utils.Settings;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

/**
 * GUI to display information about jMM
 * 
 * @author Bryan Beck
 * @since 20.10.2010
 */
public class AboutGUI extends javax.swing.JDialog{
    /** Logger. */
    private static final Logger LOG = LoggerFactory.logger(AboutGUI.class);
 
    private String payPalURL;

    /** Creates new form AboutGUI */
    public AboutGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //GUI zentriert darstellen
        this.setLocationRelativeTo(parent); 
        jLabel3.setText("v. " + Settings.currentVersion);
                
//        //Neues StyleDokument
//        StyledDocument doc = jTabbedPane1.getStyledDocument();
//        Style style = doc.addStyle( "ALIGN_JUSTIFIED", null );
//        style.addAttributes( as );
//        doc.setLogicalStyle( 0, style );
        this.setLocalizedDonation();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jMovieManager/swing/resources/MovieManager"); // NOI18N
        setTitle(bundle.getString("AboutGUI.headline")); // NOI18N
        setMinimumSize(new java.awt.Dimension(465, 475));
        setModal(true);
        setResizable(false);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(440, 410));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(440, 410));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 160));
        jPanel3.setMinimumSize(new java.awt.Dimension(285, 120));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(285, 120));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/Logo_v.1_100x100.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 100));
        jPanel3.add(jLabel2, java.awt.BorderLayout.WEST);

        jPanel8.setMinimumSize(new java.awt.Dimension(285, 100));
        jPanel8.setName(""); // NOI18N
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(285, 100));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setMinimumSize(new java.awt.Dimension(185, 20));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(185, 20));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("jMovieManager");
        jPanel10.add(jLabel1);

        jPanel8.add(jPanel10);

        jPanel11.setMinimumSize(new java.awt.Dimension(185, 20));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(185, 20));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("v. 0.6");
        jPanel11.add(jLabel3);

        jPanel8.add(jPanel11);

        jPanel9.setMinimumSize(new java.awt.Dimension(185, 20));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(185, 20));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("© 2012-2014   Bryan Beck");
        jLabel4.setToolTipText("");
        jPanel9.add(jLabel4);

        jPanel8.add(jPanel9);

        jPanel15.setMinimumSize(new java.awt.Dimension(185, 20));
        jPanel15.setOpaque(false);
        jPanel15.setPreferredSize(new java.awt.Dimension(185, 20));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("<html><u>http://jmoviemanager.de</u></html>");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel13);

        jPanel8.add(jPanel15);

        jPanel16.setMinimumSize(new java.awt.Dimension(185, 10));
        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(185, 10));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));
        jPanel8.add(jPanel16);

        jPanel3.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel3);

        jPanel4.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText(bundle.getString("AboutGUI.jLabel6")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText(bundle.getString("AboutGUI.jLabel7")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Bryan Beck");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Christian Seebach");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Bryan Beck,");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(199, 100));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(1134, 100));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("This product uses the MediaInfo library");
        jLabel10.setMaximumSize(new java.awt.Dimension(415, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(415, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(415, 25));
        jPanel5.add(jLabel10);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("to determine movie meta information.");
        jLabel12.setMaximumSize(new java.awt.Dimension(415, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(415, 25));
        jLabel12.setPreferredSize(new java.awt.Dimension(415, 25));
        jPanel5.add(jLabel12);

        jPanel1.add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 201));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 6));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton2.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jPanel1.add(jPanel6);

        jTabbedPane1.addTab(bundle.getString("AboutGUI.jPanel1"), jPanel1); // NOI18N

        jPanel17.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(bundle.getString("AboutGUI.jLabel20")); // NOI18N
        jLabel20.setMaximumSize(new java.awt.Dimension(450, 30));
        jLabel20.setMinimumSize(new java.awt.Dimension(450, 30));
        jLabel20.setPreferredSize(new java.awt.Dimension(450, 30));
        jPanel17.add(jLabel20);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, ColorInterface.list_tree_BorderShadow), bundle.getString("AboutGUI.jPanel18"))); // NOI18N
        jPanel18.setOpaque(false);
        jPanel18.setPreferredSize(new java.awt.Dimension(450, 110));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Bryan Beck (English, German)");
        jLabel19.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabel19.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabel19.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel18.add(jLabel19);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Salvador Domínguez (Spanish)");
        jLabel17.setToolTipText("");
        jLabel17.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabel17.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabel17.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel18.add(jLabel17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("André Bezerra (Portuguese)");
        jLabel18.setToolTipText("");
        jLabel18.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabel18.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabel18.setName(""); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel18.add(jLabel18);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Francesco Pavone (Italian)");
        jLabel23.setToolTipText("");
        jLabel23.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabel23.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabel23.setName(""); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel18.add(jLabel23);

        jPanel17.add(jPanel18);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, ColorInterface.list_tree_BorderShadow), bundle.getString("AboutGUI.jPanel19"))); // NOI18N
        jPanel19.setOpaque(false);
        jPanel19.setPreferredSize(new java.awt.Dimension(450, 100));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Benjamin Schunn");
        jLabel21.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabel21.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabel21.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel19.add(jLabel21);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setToolTipText("");
        jLabel22.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabel22.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabel22.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel19.add(jLabel22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(bundle.getString("AboutGUI.jLabel11")); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(400, 15));
        jLabel11.setMinimumSize(new java.awt.Dimension(400, 15));
        jLabel11.setPreferredSize(new java.awt.Dimension(400, 15));
        jPanel19.add(jLabel11);

        jPanel17.add(jPanel19);

        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel12.setMinimumSize(new java.awt.Dimension(199, 100));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(450, 140));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("This product uses the TMDb API");
        jLabel14.setMaximumSize(new java.awt.Dimension(415, 25));
        jLabel14.setMinimumSize(new java.awt.Dimension(415, 25));
        jLabel14.setPreferredSize(new java.awt.Dimension(415, 25));
        jPanel12.add(jLabel14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("but is not endorsed or certified by TMDb.");
        jLabel16.setMaximumSize(new java.awt.Dimension(415, 25));
        jLabel16.setMinimumSize(new java.awt.Dimension(415, 25));
        jLabel16.setPreferredSize(new java.awt.Dimension(415, 25));
        jPanel12.add(jLabel16);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/tmdb-logo.png"))); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(260, 60));
        jLabel15.setMinimumSize(new java.awt.Dimension(260, 60));
        jLabel15.setPreferredSize(new java.awt.Dimension(260, 60));
        jPanel12.add(jLabel15);

        jPanel17.add(jPanel12);

        jTabbedPane1.addTab(bundle.getString("AboutGUI.jPanel17"), jPanel17); // NOI18N

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(465, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(465, 40));

        jButton1.setText(bundle.getString("AboutGUI.jButton1")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * Ruft die PayPal Seite im Standardbrowser auf, um eine Spende zu tätigen
    * @param evt Event, welches ausgelöst wurde
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //PayPal Seite aufrufen
        try {
            //Öffne den Standardbrowser
            OperatingSystem.openBrowser(payPalURL); 
        } catch (IOException | URISyntaxException ex) {
            LOG.error("URL: " + payPalURL + " could not be opened in the browser.", ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * jLabel3 - Open Browser <br/>
     * Opens the default browser and leads to the jmm website
     * 
     * @param evt the triggered event 
     */
    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        try {
            OperatingSystem.openBrowser("http://jmoviemanager.de");
        } catch (IOException | URISyntaxException ex) { 
            LOG.error("URL: " + "http://jmoviemanager.de" + " could not be opened in the browser.",ex);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
    * Setzt die Grafik und die URL, um eine Spende zu tätigen
    */
    private void setLocalizedDonation(){
        Locale currentLocale = LocaleManager.getInstance().getCurrentLocale();
        
        if(currentLocale.getLanguage().equals(LocaleManager.SupportedLanguages.de_DE.getLocale().getLanguage())){
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/btn_donateCC_LG_DE.gif")));
            payPalURL ="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3NDAD63S843MN";        //DE + €
        }
        else{
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/btn_donateCC_LG_US.gif")));
            payPalURL = "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LX8YKRZMBS2RN";       //USA + $
        }
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
