/**
 * Copyright (c) 2010-2015 Bryan Beck.
 * All rights reserved.
 * 
 * This project is licensed under LGPL v2.1.
 * See jMovieManager-license.txt for details.
 * 
 */
package jMovieManager.swing.gui;

import jMovieManager.swing.gui.other.ImageTableCellRenderer;
import jMovieManager.swing.gui.other.ImageTableModel;
import java.util.LinkedList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import jmm.api.thetvdb.TheTVDBSeries;
import jmm.data.LocalVideoFile;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

/**
 * GUI to choose a search result
 * 
 * @author Bryan Beck
 * @since 31.10.2012
 */
public class ChooseMediaFileDialog<T extends LocalVideoFile> extends javax.swing.JDialog  implements UIInterface{
    /** Logger. */
    private static final Logger LOG = LoggerFactory.logger(ChooseMediaFileDialog.class);
    
    private List<T> searchResults;
    private ResourceBundle bundle;   
    private boolean canceled;
    private DefaultTableModel tableModel;
    //TODO: Performance Problem, GUI überarbeiten. BEi mehr als 10 Ergebnissen stockt alles
    
    /**
     * Creates new form ChooseMediaFileDialog
     * 
     * @param title the Title of the MediaFile which was not found
     * @param searchResults the search results to display
     * @see JDialog
     */
    public ChooseMediaFileDialog(java.awt.Frame parent, boolean modal, String title,  List<T> searchResults){
        super(parent, modal);
        bundle = ResourceBundle.getBundle("jMovieManager.swing.resources.MovieManager"); 
        tableModel = new ImageTableModel();
        initComponents();
        initTable();
        this.setLocationRelativeTo(parent);

        if(useCustomLAF){
            this.changeUI();
        }
                
        canceled = false;        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                canceled = true;
                jButton1ActionPerformed(null);
            }
        });
        
        jLabel3.setText('"' + title + '"');
        this.searchResults = new LinkedList<T>();
        for(T result: searchResults){
            this.searchResults.add(result);
        }       
        insertSimilarTitles();
    }

    /**
     * @return the canceled
     */
    public boolean isCanceled() {
        return canceled;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(bundle.getString("ChooseMediaFileDialogGUI.headline"));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 595));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, ColorInterface.list_tree_BorderShadow));

        jTable1.setModel(tableModel);
        jTable1.setFocusable(false);
        jTable1.setRowHeight(143);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowVerticalLines(false);
        jTable1.setTableHeader(null);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 125));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 125));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 125));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jMovieManager/swing/resources/MovieManager"); // NOI18N
        jLabel1.setText(bundle.getString("ChooseMediaFileDialogGUI.jLabel1")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(bundle.getString("ChooseMediaFileDialogGUI.jLabel4")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("ChooseMediaFileDialogGUI.jLabel2")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel3.setMinimumSize(new java.awt.Dimension(80, 35));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 35));

        jButton1.setText(bundle.getString("ChooseMediaFileDialogGUI.jButton1")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setEnabled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(70, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * jButton 1 - OK <br/>
     * Disposes the GUI
     * 
     * @param evt the triggered event
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * jTable1 - Enable OK Button <br/>
     * Enables the OK Button if a element is selected
     * @param evt the triggered event
     */
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if(jTable1.getSelectedRow() >-1){
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * jTable1 - Press OK Button <br/>
     * Presses the OK Button if a doubleclick was on a selected file
     * @param evt the triggered event
     */    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if((jTable1.getSelectedRow() >-1) && (evt.getClickCount() > 1)){
            this.jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTable1MouseClicked
   
    /**
     * initialize the table
     */
    private void initTable(){               
        ImageTableCellRenderer tableCellRenderer = new ImageTableCellRenderer();
//        jTable1.setDefaultRenderer(String.class,  new ImageTableCellRenderer());
        jTable1.getColumnModel().getColumn(0).setCellRenderer(tableCellRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(tableCellRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(tableCellRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(tableCellRenderer);
           
        jTable1.getColumnModel().getColumn(0).setWidth(100);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setWidth(500);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(500);
        jTable1.getColumnModel().getColumn(2).setWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100); 
        jTable1.getColumnModel().getColumn(3).setWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
    }
    
  /**
    * Inserts the search results into the table model 
    */
    private void insertSimilarTitles(){
        for(T result : searchResults){
            if(!result.getTitle().isEmpty()){
                String rlsYearString;
                if(result.getReleaseYear() == 0){
                    rlsYearString = "";
                }else{
                    rlsYearString = String.valueOf(result.getReleaseYear());
                }
                
                if(result instanceof TheTVDBSeries){                  
                    tableModel.addRow(new Object[]{result.getImagePath(), result.getTitle(),
                        rlsYearString, bundle.getString("ChooseMediaFileDialogGUI.series")});  
                }
                else{      
                    tableModel.addRow(new Object[]{result.getImagePath(), result.getTitle(),
                        rlsYearString, bundle.getString("ChooseMediaFileDialogGUI.movie")});  
                }
            }
        }
    }

    /**
    * Shows the GUI and returns the selected result.
    * @return The selected result <br/> null, if the dialog was canceled
    **/
    public T showDialog(){
        this.setVisible(true);
        //Wird erst nach dem Klick auf OK ausgeführt:
        if(!isCanceled()){
            int index = jTable1.getSelectedRow();
            if(index > -1){
                return searchResults.get(index);
            }
        }
        return null;
    }
    
    /**
    * Methode zum Anpassen der GUI an das neue Look and Feel
    **/
    @Override
   public void changeUI(){
        jLabel3.setForeground(UIManager.getColor("TextField.foreground"));    
        jLabel2.setForeground(UIManager.getColor("TextField.foreground"));  
   }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
