/**
 * Copyright (c) 2010-2015 Bryan Beck.
 * All rights reserved.
 * 
 * This project is licensed under LGPL v2.1.
 * See jMovieManager-license.txt for details.
 * 
 */
package jMovieManager.swing.gui;

import jMovieManager.swing.gui.components.ui.MyBasicMenuButtonUI;
import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.DefaultListModel;
import jmm.data.Actor;
import jmm.data.MediaFile;
import jmm.data.collection.MediaCollection;
import jmm.interfaces.FileTypeInterface;
import jmm.interfaces.GenreKeysInterface;
import jMovieManager.swing.gui.components.ui.MyBasicScrollBarUI;
import javax.swing.DefaultComboBoxModel;
import javax.swing.plaf.basic.BasicButtonUI;
import jmm.data.VideoFile.FSK;
import jmm.data.collection.MovieCollection;
import jmm.data.collection.SerieCollection;
import jmm.utils.ExtendedSearch;
import jmm.utils.LocaleManager;
import jmm.utils.MaxLengthDocument;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

/**
 * Erweiterte Suchfunktion, der die jList Filme anhand von Kriterien wie (Schauspieler, Genre, Laufzeit, ...) einschränkt  
 * 
 * @author Bryan Beck
 * @since 14.05.2011
 */
public class ExtendedSearchGUI extends javax.swing.JDialog implements GenreKeysInterface, UIInterface, FileTypeInterface, Observer{   
    /** Logger. */
    private static final Logger LOG = LoggerFactory.logger(ExtendedSearchGUI.class);
    
    private MediaCollection collection;
    private MediaType searchType;
    
    private String title;
    private String oTitle;
    private Set<String> genreKeys;
    private int playtimeFrom;
    private int playtimeTo;
    private int rlsYearFrom;
    private int rlsYearTo;
    private int widthFrom;
    private int heightFrom;
    private int widthTo;
    private int heightTo;    
    private String publisher;
    private Set<String> actors;
    private String director;
    private double imdbRatingFrom; 
    private double imdbRatingTo;
    private double persRatingFrom;
    private double persRatingTo;
    private List<FSK> fskList;
    private Boolean watched;
    
    private boolean canceled;
    private DefaultComboBoxModel collectionComboBoxModel;
    private DefaultListModel genresListModel;
    //LocalizedGenre, genreKey
    private Map<String, String> genresMap;
        
    //Singelton Instanz
    public static ExtendedSearchGUI instance;
    private ResourceBundle bundle;
    private ResourceBundle genreKeyAndCodecBundle;
    
    /** Creates new form ExtendedSearchGUI */
    private ExtendedSearchGUI(java.awt.Frame parent, boolean modal){
        //TODO: Search Music/Episodes option
        super(parent, modal);
        bundle = ResourceBundle.getBundle("jMovieManager.swing.resources.MovieManager");
        genreKeyAndCodecBundle = LocaleManager.getInstance().getGenreKeyAndCodecBundle();
                        
        searchType = MediaType.MOVIE;
        collectionComboBoxModel = new DefaultComboBoxModel();
        updateCollectionComboBox();
        
        genresListModel = new DefaultListModel();
        genreKeys = new HashSet<String> ();
        actors = new HashSet<String> ();
        fskList = new LinkedList<FSK>();
        genresMap = new TreeMap<String, String>(new Comparator<String>() {
                /**
                * Order key by name. A-Z
                * @param o1 - the first object to be compared.
                * @param o2 - the second object to be compared.
                *
                * @return a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second.
                */
                @Override
                public int compare(String o1, String o2) {
                    return (o1.compareToIgnoreCase(o2));
                }
            }
        );
        canceled = false;

        addGenresToModel();
        initComponents();
        this.setLocationRelativeTo(parent);
        
        if(useCustomLAF){
            this.changeUI();
        }
        
        //Füge eigene Methode bei Fensterschließen hinzu
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                canceled = true;
                //dispose();
                setVisible(false);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel29 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel30 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel42 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel38 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel18 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel34 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel35 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jMovieManager/swing/resources/MovieManager"); // NOI18N
        setTitle(bundle.getString("ExtendedSearchGUI.headline")); // NOI18N
        setMinimumSize(new java.awt.Dimension(520, 655));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(520, 505));

        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(495, 500));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(555, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(10, 456));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(10, 456));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(555, 265));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText(bundle.getString("ExtendedSearchGUI.jLabel2")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel4.add(jLabel2);

        jPanel28.setMaximumSize(new java.awt.Dimension(50, 15));
        jPanel28.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel28.setOpaque(false);
        jPanel28.setPreferredSize(new java.awt.Dimension(50, 15));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel28);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(bundle.getString("ExtendedSearchGUI.jRadioButton1")); // NOI18N
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1);

        jPanel29.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel29.setOpaque(false);
        jPanel29.setPreferredSize(new java.awt.Dimension(100, 15));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel29);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(bundle.getString("ExtendedSearchGUI.jRadioButton2")); // NOI18N
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2);

        jPanel30.setMaximumSize(new java.awt.Dimension(100, 15));
        jPanel30.setMinimumSize(new java.awt.Dimension(100, 15));
        jPanel30.setOpaque(false);
        jPanel30.setPreferredSize(new java.awt.Dimension(100, 15));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel30);

        jPanel3.add(jPanel4);

        jPanel41.setOpaque(false);
        jPanel41.setLayout(new javax.swing.BoxLayout(jPanel41, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText(bundle.getString("ExtendedSearchGUI.jLabel11")); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel11.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel11.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel41.add(jLabel11);

        jComboBox1.setModel(collectionComboBoxModel);
        jPanel41.add(jComboBox1);

        jPanel3.add(jPanel41);

        jPanel42.setOpaque(false);
        jPanel42.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel42);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(bundle.getString("ExtendedSearchGUI.jLabel1")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel5.add(jLabel1);

        jTextField1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel5.add(jTextField1);

        jPanel3.add(jPanel5);

        jPanel20.setOpaque(false);
        jPanel20.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel20);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText(bundle.getString("ExtendedSearchGUI.jLabel3")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel9.add(jLabel3);

        jTextField2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel9.add(jTextField2);

        jPanel3.add(jPanel9);

        jPanel21.setOpaque(false);
        jPanel21.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel21);

        jPanel36.setMinimumSize(new java.awt.Dimension(440, 65));
        jPanel36.setOpaque(false);
        jPanel36.setPreferredSize(new java.awt.Dimension(440, 65));
        jPanel36.setLayout(new javax.swing.BoxLayout(jPanel36, javax.swing.BoxLayout.LINE_AXIS));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText(bundle.getString("ExtendedSearchGUI.jLabel21")); // NOI18N
        jLabel21.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel21.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel21.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel36.add(jLabel21);

        jPanel37.setOpaque(false);
        jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 0));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/fsk/FSK-0.png"))); // NOI18N
        jButton3.setToolTipText(bundle.getString("FSK.0.tooltip")); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(65, 65));
        jButton3.setMinimumSize(new java.awt.Dimension(65, 65));
        jButton3.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton3);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/fsk/FSK-6.png"))); // NOI18N
        jButton6.setToolTipText(bundle.getString("FSK.6.tooltip")); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setMaximumSize(new java.awt.Dimension(65, 65));
        jButton6.setMinimumSize(new java.awt.Dimension(65, 65));
        jButton6.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/fsk/FSK-12.png"))); // NOI18N
        jButton7.setToolTipText(bundle.getString("FSK.12.tooltip")); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setMaximumSize(new java.awt.Dimension(65, 65));
        jButton7.setMinimumSize(new java.awt.Dimension(65, 65));
        jButton7.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/fsk/FSK-16.png"))); // NOI18N
        jButton8.setToolTipText(bundle.getString("FSK.16.tooltip")); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setMaximumSize(new java.awt.Dimension(65, 65));
        jButton8.setMinimumSize(new java.awt.Dimension(65, 65));
        jButton8.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jMovieManager/swing/images/fsk/FSK-18.png"))); // NOI18N
        jButton9.setToolTipText(bundle.getString("FSK.18.tooltip")); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setMaximumSize(new java.awt.Dimension(55, 55));
        jButton9.setMinimumSize(new java.awt.Dimension(65, 65));
        jButton9.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton9);

        jPanel36.add(jPanel37);

        jPanel3.add(jPanel36);

        jPanel38.setOpaque(false);
        jPanel38.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel38);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText(bundle.getString("ExtendedSearchGUI.jLabel4")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel4.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel4.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel10.add(jLabel4);

        jList1.setModel(genresListModel);
        jScrollPane2.setViewportView(jList1);

        jPanel10.add(jScrollPane2);

        jPanel3.add(jPanel10);

        jPanel18.setOpaque(false);
        jPanel18.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel18);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText(bundle.getString("ExtendedSearchGUI.jLabel5")); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel5.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel5.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel11.add(jLabel5);

        jTextField3.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField3.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField3.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel11.add(jTextField3);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(bundle.getString("ExtendedSearchGUI.jLabel19")); // NOI18N
        jLabel19.setMaximumSize(new java.awt.Dimension(26, 15));
        jLabel19.setMinimumSize(new java.awt.Dimension(26, 15));
        jLabel19.setPreferredSize(new java.awt.Dimension(26, 15));
        jPanel11.add(jLabel19);

        jTextField4.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField4.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel11.add(jTextField4);

        jPanel3.add(jPanel11);

        jPanel19.setOpaque(false);
        jPanel19.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel19);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText(bundle.getString("ExtendedSearchGUI.jLabel6")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel6.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel6.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel12.add(jLabel6);

        jTextField5.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField5.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField5.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel12.add(jTextField5);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(bundle.getString("ExtendedSearchGUI.jLabel16")); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(26, 15));
        jLabel16.setMinimumSize(new java.awt.Dimension(26, 15));
        jLabel16.setPreferredSize(new java.awt.Dimension(26, 15));
        jPanel12.add(jLabel16);

        jTextField6.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField6.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField6.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel12.add(jTextField6);

        jPanel3.add(jPanel12);

        jPanel39.setOpaque(false);
        jPanel39.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel39);

        jPanel40.setOpaque(false);
        jPanel40.setLayout(new javax.swing.BoxLayout(jPanel40, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText(bundle.getString("ExtendedSearchGUI.jLabel10")); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel10.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel10.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel40.add(jLabel10);

        jTextField10.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField10.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField10.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel40.add(jTextField10);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("x");
        jLabel22.setMaximumSize(new java.awt.Dimension(26, 15));
        jLabel22.setMinimumSize(new java.awt.Dimension(26, 15));
        jLabel22.setPreferredSize(new java.awt.Dimension(26, 15));
        jPanel40.add(jLabel22);

        jTextField15.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField15.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField15.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel40.add(jTextField15);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(bundle.getString("ExtendedSearchGUI.jLabel23")); // NOI18N
        jLabel23.setMaximumSize(new java.awt.Dimension(26, 15));
        jLabel23.setMinimumSize(new java.awt.Dimension(26, 15));
        jLabel23.setPreferredSize(new java.awt.Dimension(26, 15));
        jPanel40.add(jLabel23);

        jTextField16.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField16.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField16.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel40.add(jTextField16);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("x");
        jLabel24.setMaximumSize(new java.awt.Dimension(26, 15));
        jLabel24.setMinimumSize(new java.awt.Dimension(26, 15));
        jLabel24.setPreferredSize(new java.awt.Dimension(26, 15));
        jPanel40.add(jLabel24);

        jTextField17.setDocument(new MaxLengthDocument(4, MaxLengthDocument.INTEGER));
        jTextField17.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField17.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel40.add(jTextField17);

        jPanel3.add(jPanel40);

        jPanel22.setOpaque(false);
        jPanel22.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel22);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText(bundle.getString("ExtendedSearchGUI.jLabel7")); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel7.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel7.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel13.add(jLabel7);

        jTextField7.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel13.add(jTextField7);

        jPanel3.add(jPanel13);

        jPanel23.setOpaque(false);
        jPanel23.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel23);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText(bundle.getString("ExtendedSearchGUI.jLabel8")); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel8.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel8.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel14.add(jLabel8);

        jTextField8.setPreferredSize(new java.awt.Dimension(50, 20));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel14.add(jTextField8);

        jPanel3.add(jPanel14);

        jPanel24.setOpaque(false);
        jPanel24.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel24);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText(bundle.getString("ExtendedSearchGUI.jLabel9")); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel9.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel9.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel15.add(jLabel9);

        jTextField9.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel15.add(jTextField9);

        jPanel3.add(jPanel15);

        jPanel25.setOpaque(false);
        jPanel25.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel25);

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText(bundle.getString("ExtendedSearchGUI.jLabel14")); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel14.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel14.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel16.add(jLabel14);

        jTextField11.setDocument(new MaxLengthDocument(3, MaxLengthDocument.DOUBLE));
        jTextField11.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField11.setPreferredSize(new java.awt.Dimension(20, 20));
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jPanel16.add(jTextField11);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(bundle.getString("ExtendedSearchGUI.jLabel17")); // NOI18N
        jLabel17.setMaximumSize(new java.awt.Dimension(26, 15));
        jLabel17.setMinimumSize(new java.awt.Dimension(26, 15));
        jLabel17.setPreferredSize(new java.awt.Dimension(26, 15));
        jPanel16.add(jLabel17);

        jTextField12.setDocument(new MaxLengthDocument(3, MaxLengthDocument.DOUBLE));
        jTextField12.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField12.setPreferredSize(new java.awt.Dimension(20, 20));
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });
        jPanel16.add(jTextField12);

        jPanel3.add(jPanel16);

        jPanel26.setOpaque(false);
        jPanel26.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel26);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText(bundle.getString("ExtendedSearchGUI.jLabel15")); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel15.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel15.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel17.add(jLabel15);

        jTextField13.setDocument(new MaxLengthDocument(3, MaxLengthDocument.DOUBLE));
        jTextField13.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField13.setPreferredSize(new java.awt.Dimension(20, 20));
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });
        jPanel17.add(jTextField13);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(bundle.getString("ExtendedSearchGUI.jLabel18")); // NOI18N
        jLabel18.setMaximumSize(new java.awt.Dimension(26, 15));
        jLabel18.setMinimumSize(new java.awt.Dimension(26, 15));
        jLabel18.setPreferredSize(new java.awt.Dimension(26, 15));
        jPanel17.add(jLabel18);

        jTextField14.setDocument(new MaxLengthDocument(3, MaxLengthDocument.DOUBLE));
        jTextField14.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField14.setPreferredSize(new java.awt.Dimension(20, 20));
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField14FocusLost(evt);
            }
        });
        jPanel17.add(jTextField14);

        jPanel3.add(jPanel17);

        jPanel27.setOpaque(false);
        jPanel27.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel27);

        jPanel31.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel31.setMinimumSize(new java.awt.Dimension(176, 20));
        jPanel31.setOpaque(false);
        jPanel31.setPreferredSize(new java.awt.Dimension(176, 20));
        jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31, javax.swing.BoxLayout.LINE_AXIS));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText(bundle.getString("ExtendedSearchGUI.jLabel20")); // NOI18N
        jLabel20.setMaximumSize(new java.awt.Dimension(110, 15));
        jLabel20.setMinimumSize(new java.awt.Dimension(110, 15));
        jLabel20.setPreferredSize(new java.awt.Dimension(110, 15));
        jPanel31.add(jLabel20);

        jPanel33.setMaximumSize(new java.awt.Dimension(50, 15));
        jPanel33.setMinimumSize(new java.awt.Dimension(50, 15));
        jPanel33.setOpaque(false);

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel33);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText(bundle.getString("ExtendedSearchGUI.jRadioButton3")); // NOI18N
        jRadioButton3.setMaximumSize(new java.awt.Dimension(75, 23));
        jRadioButton3.setMinimumSize(new java.awt.Dimension(75, 23));
        jRadioButton3.setOpaque(false);
        jRadioButton3.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel31.add(jRadioButton3);

        jPanel34.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel34.setOpaque(false);
        jPanel34.setPreferredSize(new java.awt.Dimension(100, 15));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel34);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText(bundle.getString("ExtendedSearchGUI.jRadioButton4")); // NOI18N
        jRadioButton4.setMaximumSize(new java.awt.Dimension(75, 23));
        jRadioButton4.setMinimumSize(new java.awt.Dimension(75, 23));
        jRadioButton4.setOpaque(false);
        jRadioButton4.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel31.add(jRadioButton4);

        jPanel35.setMaximumSize(new java.awt.Dimension(100, 15));
        jPanel35.setMinimumSize(new java.awt.Dimension(100, 15));
        jPanel35.setOpaque(false);

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel35);

        jPanel3.add(jPanel31);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel32.setMinimumSize(new java.awt.Dimension(225, 45));
        jPanel32.setPreferredSize(new java.awt.Dimension(498, 45));
        jPanel32.setLayout(new javax.swing.BoxLayout(jPanel32, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel32.add(jSeparator1);

        jPanel1.setPreferredSize(new java.awt.Dimension(555, 35));

        jButton1.setText(bundle.getString("ExtendedSearchGUI.jButton1")); // NOI18N
        jButton1.setActionCommand("jButton1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(110, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(110, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(110, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jPanel1.add(filler1);

        jButton2.setText(bundle.getString("ExtendedSearchGUI.jButton2")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(110, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(110, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(110, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jPanel32.add(jPanel1);

        jPanel2.add(jPanel32, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Zurücksetzten Button
     * 
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jList1.clearSelection();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        //resolution
        jTextField10.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jComboBox1.setSelectedIndex(0);
        
        buttonGroup2.clearSelection();
        jButton3.setSelected(false);
        jButton6.setSelected(false);
        jButton7.setSelected(false);
        jButton8.setSelected(false);
        jButton9.setSelected(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Filter Button
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        genreKeys.clear();
        actors.clear();
        fskList.clear();
        if(jRadioButton1.isSelected()){
            searchType = MediaType.MOVIE;
        }
        else if(jRadioButton2.isSelected()){
            searchType = MediaType.SERIE;
        } 
        
        if(jComboBox1.getSelectedItem() instanceof MediaCollection){
            collection = (MediaCollection)jComboBox1.getSelectedItem();
        }else{
            collection = null;
        }     
        
        try{
            playtimeFrom = Integer.parseInt(jTextField3.getText());      
        }
        catch(NumberFormatException evt2){
            playtimeFrom = 0;
        }
        try{
            playtimeTo = Integer.parseInt(jTextField4.getText());
        }
        catch(NumberFormatException evt2){
            playtimeTo = 0;
        }
        try{
            rlsYearFrom = Integer.parseInt(jTextField5.getText());
        }
        catch(NumberFormatException evt2){
            rlsYearFrom = 0;
        }
        try{
            rlsYearTo = Integer.parseInt(jTextField6.getText());
        }
        catch(NumberFormatException evt2){
            rlsYearTo = 0;
        }   
        try{
            widthFrom = Integer.parseInt(jTextField10.getText());
        }
        catch(NumberFormatException evt2){
            widthFrom = 0;
        } 
                try{
            heightFrom = Integer.parseInt(jTextField15.getText());
        }
        catch(NumberFormatException evt2){
            heightFrom = 0;
        } 
        try{
            widthTo = Integer.parseInt(jTextField16.getText());
        }
        catch(NumberFormatException evt2){
            widthTo = 0;
        } 
                try{
            heightTo = Integer.parseInt(jTextField17.getText());
        }
        catch(NumberFormatException evt2){
            heightTo = 0;
        }                 
        try{
            imdbRatingFrom = Double.parseDouble(jTextField11.getText());
        }
        catch(NumberFormatException evt2){
            imdbRatingFrom = 0;
        } 
        try{
            imdbRatingTo = Double.parseDouble(jTextField12.getText());
        }
        catch(NumberFormatException evt2){
            imdbRatingTo = 0;
        }   
        try{
            persRatingFrom = Double.parseDouble(jTextField13.getText());
        }
        catch(NumberFormatException evt2){
            persRatingFrom = 0;
        }   
        try{
            persRatingTo = Double.parseDouble(jTextField14.getText()); 
        }
        catch(NumberFormatException evt2){
            persRatingTo = 0;
        }           
        if(jRadioButton3.isSelected()){
            watched = true;
        }
        else if(jRadioButton4.isSelected()){
            watched = false;                    
        }
        else{
            watched = null;
        }
        
        //FSK
        if(jButton3.isSelected()){
            fskList.add(FSK.FSK_0);
        }
        if(jButton6.isSelected()){
            fskList.add(FSK.FSK_6);
        }
        if(jButton7.isSelected()){
            fskList.add(FSK.FSK_12);
        }
        if(jButton8.isSelected()){
            fskList.add(FSK.FSK_16);
        }
        if(jButton9.isSelected()){
            fskList.add(FSK.FSK_18);
        }
        
        title = jTextField1.getText();
        oTitle = jTextField2.getText();
        for (Iterator it = jList1.getSelectedValuesList().iterator(); it.hasNext();) {
            Object value = it.next();
            genreKeys.add(genresMap.get(value.toString()));
        }        
        publisher = jTextField7.getText();
        
        if(!jTextField8.getText().isEmpty()){
            String[] actorsArray = jTextField8.getText().split(", ");
            actors.addAll(Arrays.asList(actorsArray));
        }
        
        director = jTextField9.getText();
        //this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Überprüft, ob im Feld eine Zahl steht und diese kleiner als 10 ist
     *
     * @param evt Event, welches ausgelöst wurde
     */    
    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        if(!jTextField11.getText().isEmpty()){
            boolean isRating;
            try{
                isRating = (Double.parseDouble(jTextField11.getText()) <= 10);               
            }catch(NumberFormatException ex){
                isRating = false;
            }
            if(!isRating){
                //Setzte den Fokus wieder in das Textfeld
                javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("AbstractCreateGUI.error.jTextField6.number"));            
                jTextField11.requestFocusInWindow();
                jButton1.setEnabled(false);
            }
        }
        else{
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField11FocusLost

    /**
     * Überprüft, ob im Feld eine Zahl steht und diese kleiner als 10 ist
     *
     * @param evt Event, welches ausgelöst wurde
     */    
    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        if(!jTextField12.getText().isEmpty()){
            boolean isRating;
            try{
                isRating = (Double.parseDouble(jTextField12.getText()) <= 10);               
            }catch(NumberFormatException ex){
                isRating = false;
            }
            if(!isRating){
                //Setzte den Fokus wieder in das Textfeld
                javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("AbstractCreateGUI.error.jTextField6.number"));            
                jTextField12.requestFocusInWindow();
                jButton1.setEnabled(false);
            }
        }
        else{
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField12FocusLost

    /**
     * Überprüft, ob im Feld eine Zahl steht und diese kleiner als 10 ist
     *
     * @param evt Event, welches ausgelöst wurde
     */    
    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        if(!jTextField13.getText().isEmpty()){
            boolean isRating;
            try{
                isRating = (Double.parseDouble(jTextField13.getText()) <= 10);               
            }catch(NumberFormatException ex){
                isRating = false;
            }
            if(!isRating){
                //Setzte den Fokus wieder in das Textfeld
                javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("AbstractCreateGUI.error.jTextField6.number"));            
                jTextField13.requestFocusInWindow();
                jButton1.setEnabled(false);
            }
        }
        else{
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField13FocusLost

    /**
     * Überprüft, ob im Feld eine Zahl steht und diese kleiner als 10 ist
     *
     * @param evt Event, welches ausgelöst wurde
     */    
    private void jTextField14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusLost
        if(!jTextField14.getText().isEmpty()){
            boolean isRating;
            try{
                isRating = (Double.parseDouble(jTextField14.getText()) <= 10);               
            }catch(NumberFormatException ex){
                isRating = false;
            }
            if(!isRating){
                //Setzte den Fokus wieder in das Textfeld
                javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("AbstractCreateGUI.error.jTextField6.number"));            
                jTextField14.requestFocusInWindow();
                jButton1.setEnabled(false);
            }
        }
        else{
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField14FocusLost

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        if(!(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_DELETE) || (evt.getKeyChar() == KeyEvent.VK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_COMMA)){
            //Suchanfrage
            int index = jTextField8.getText().lastIndexOf(", ");
            String actorToSearch;
            if(index > -1){
                actorToSearch = jTextField8.getText().substring(index+2);
            }
            else{
                actorToSearch = jTextField8.getText();
            }
            if((!actorToSearch.isEmpty()) && (actorToSearch.length() > 2)){
                for(Actor actor: Actor.getActorsSet()){
                    if(actor.getName().startsWith(actorToSearch)){
                        int oldSize = jTextField8.getText().length();
                        jTextField8.setText(jTextField8.getText() + actor.getName().substring(actorToSearch.length()) + ", ");
                        jTextField8.select(oldSize, jTextField8.getText().length());                   
                        break;
                    }
                }   
            }
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setSelected(!jButton3.isSelected());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setSelected(!jButton6.isSelected());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setSelected(!jButton7.isSelected());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jButton8.setSelected(!jButton8.isSelected());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jButton9.setSelected(!jButton9.isSelected());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        searchType = MediaType.SERIE;
        updateCollectionComboBox();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        searchType = MediaType.MOVIE;
        updateCollectionComboBox();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
    * Methode zum erstellen bzw. zur Rückgabe einer Singleton Instanz
    *
    * @return instance - The instance of the mediaFilterGUI class
    */
    public static ExtendedSearchGUI getInstance(){
        if(instance == null){
            instance = new ExtendedSearchGUI(MovieManagerGUI.getInstance(), true);
            //Add Observer
            LocaleManager.getInstance().addObserver(instance);
        }
        return instance;
    }
    
    /**
     * Updates the content of the collection combo box
     */
    private void updateCollectionComboBox(){
        collectionComboBoxModel.removeAllElements();
        collectionComboBoxModel.addElement(bundle.getString("ExtendedSearchGUI.jComboBox1.entry"));
        for(MediaCollection value: MediaCollection.getCollectionMap().values()){
            if(((searchType.equals(MediaType.MOVIE) && value instanceof MovieCollection)) ||
                    ((searchType.equals(MediaType.SERIE) && value instanceof SerieCollection))) {
                collectionComboBoxModel.addElement(value);
           }
        }
        collectionComboBoxModel.setSelectedItem(bundle.getString("ExtendedSearchGUI.jComboBox1.entry"));
    }
        
    /**
     * Methode welche dem Jlist1Model Genres, als auch die zugehörigen Einträge der HashMap hinzufügt
     */
    private void addGenresToModel(){   
        for(String genreKey: GENRE_KEYS){
            //Füge die Genres einer Hashmap hinzu, damit nach Auswahl nicht Lokalisierte Wert gespeichert werden kann 
            if(genreKeyAndCodecBundle.containsKey(genreKey)){
                genresMap.put(genreKeyAndCodecBundle.getString(genreKey), genreKey);
                genresListModel.addElement(genreKeyAndCodecBundle.getString(genreKey));
            }
        }
    }
    
    /**
    * Observer method for locale update <br/>
    * Updates all localized GUI elements
    * 
    * @param o the observerable object
    * @param arg the updated locale
    */
   @Override
    public void update(Observable o, Object arg) {
       if(arg instanceof Locale){
           updateGUILocalization();
       }
    }
    
   /**
   * Aktualisiert alle Labels, Buttons, Tooltips und sonstigen Texte der GUI
   * auf das gesetzte Locale
   */
   private void updateGUILocalization(){
       bundle = ResourceBundle.getBundle("jMovieManager.swing.resources.MovieManager");
       genreKeyAndCodecBundle = LocaleManager.getInstance().getGenreKeyAndCodecBundle();
       
       this.setTitle(bundle.getString("ExtendedSearchGUI.headline"));
       jButton1.setText(bundle.getString("ExtendedSearchGUI.jButton1"));
       jButton2.setText(bundle.getString("ExtendedSearchGUI.jButton2"));
       jLabel1.setText(bundle.getString("ExtendedSearchGUI.jLabel1"));
       jLabel2.setText(bundle.getString("ExtendedSearchGUI.jLabel2"));
       jLabel3.setText(bundle.getString("ExtendedSearchGUI.jLabel3"));
       jLabel4.setText(bundle.getString("ExtendedSearchGUI.jLabel4"));
       jLabel5.setText(bundle.getString("ExtendedSearchGUI.jLabel5"));
       jLabel6.setText(bundle.getString("ExtendedSearchGUI.jLabel6"));
       jLabel7.setText(bundle.getString("ExtendedSearchGUI.jLabel7"));
       jLabel8.setText(bundle.getString("ExtendedSearchGUI.jLabel8"));
       jLabel9.setText(bundle.getString("ExtendedSearchGUI.jLabel9"));
       jLabel10.setText(bundle.getString("ExtendedSearchGUI.jLabel10"));       
       jLabel14.setText(bundle.getString("ExtendedSearchGUI.jLabel14"));
       jLabel15.setText(bundle.getString("ExtendedSearchGUI.jLabel15"));
       jLabel16.setText(bundle.getString("ExtendedSearchGUI.jLabel16"));
       jLabel17.setText(bundle.getString("ExtendedSearchGUI.jLabel17"));
       jLabel18.setText(bundle.getString("ExtendedSearchGUI.jLabel19"));
       jLabel19.setText(bundle.getString("ExtendedSearchGUI.jLabel19"));
       jLabel20.setText(bundle.getString("ExtendedSearchGUI.jLabel20"));
       jLabel21.setText(bundle.getString("ExtendedSearchGUI.jLabel21"));
       jLabel23.setText(bundle.getString("ExtendedSearchGUI.jLabel23"));
       
       jRadioButton1.setText(bundle.getString("ExtendedSearchGUI.jRadioButton1"));
       jRadioButton2.setText(bundle.getString("ExtendedSearchGUI.jRadioButton2"));
       jRadioButton3.setText(bundle.getString("ExtendedSearchGUI.jRadioButton3"));
       jRadioButton4.setText(bundle.getString("ExtendedSearchGUI.jRadioButton4"));       
       updateCollectionComboBox();
       
       jButton3.setToolTipText(bundle.getString("FSK.0.tooltip"));  
       jButton6.setToolTipText(bundle.getString("FSK.6.tooltip"));  
       jButton7.setToolTipText(bundle.getString("FSK.12.tooltip"));  
       jButton8.setToolTipText(bundle.getString("FSK.16.tooltip"));  
       jButton9.setToolTipText(bundle.getString("FSK.18.tooltip"));  

       genresListModel.removeAllElements();
       addGenresToModel();
       jList1.setModel(genresListModel);
   }
    
    /**
     * 
     * Macht die GUI sichtbar und gibt die gefilterten Elemente zurück
     * 
     * @return Liste der gefilterten Movie Elemente
     */
    public MediaCollection<? extends MediaFile> showFilterGUI(){
        this.setVisible(true);    
                
        if(canceled){
            canceled = false;
            return null;
        }
        
        //Filtere Datenbestand
        ExtendedSearch filter = ExtendedSearch.getInstance();
        
        if(searchType == MediaType.MOVIE){
        filter.filterMovies(
                bundle.getString("ExtendedSearchGUI.tabName"), //collection title
                (collection != null)? (MovieCollection)collection: null, //Collection
                title,                       //Titel
                oTitle,                      //oTitel
                genreKeys,                   //Genres
                playtimeFrom,                //PlaytimeFrom
                playtimeTo,                  //PlaytimeTo
                rlsYearFrom,                 //RlsDateFrom
                rlsYearTo,                   //RlsDateTo
                widthFrom,
                heightFrom,
                widthTo,
                heightTo,
                publisher,                   //Publisher
                actors,                      //Actors
                director,                    //Director  
                imdbRatingFrom,              //ImdbRatingFrom
                imdbRatingTo,                //ImdbRatingTo
                persRatingFrom,              //PersRatingFrom
                persRatingTo,                //PersRatingTo
                fskList,
                watched);
        }
        else if(searchType == MediaType.SERIE){
        filter.filterSeries(
                bundle.getString("ExtendedSearchGUI.tabName"), //collection title
                (collection != null)? (SerieCollection)collection: null,
                title,                       //Titel
                oTitle,                      //oTitel
                genreKeys,                   //Genres
                playtimeFrom,                //PlaytimeFrom
                playtimeTo,                  //PlaytimeTo
                rlsYearFrom,                 //RlsDateFrom
                rlsYearTo,                   //RlsDateTo
                publisher,                   //Publisher
                actors,                      //Actors
                director,                    //Director  
                imdbRatingFrom,              //ImdbRatingFrom
                imdbRatingTo,                //ImdbRatingTo
                persRatingFrom,              //PersRatingFrom
                persRatingTo,                //PersRatingTo
                fskList);
        }
        //Gebe die gefilterten Filmelemente zurück
        return filter.getSearchCollection();
    }    
    
   /**
    * Methode zum Anpassen der GUI an das neue Look and Feel
    **/
    @Override
   public void changeUI(){
        jPanel2.setBackground(ColorInterface.list_tree_Background);
        jScrollPane1.getHorizontalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jList1)); 
        jScrollPane1.getVerticalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jList1));  
        jScrollPane2.getHorizontalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jPanel2));  
        jScrollPane2.getVerticalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jPanel2));   
//                   jButton1.setUI((MyBasicButtonUI)MyBasicButtonUI.createUI(jButton1));
//                   jButton2.setUI((MyBasicButtonUI)MyBasicButtonUI.createUI(jButton2));
              
        jButton3.setUI((BasicButtonUI)MyBasicMenuButtonUI.createUI(jButton3));
        jButton6.setUI((BasicButtonUI)MyBasicMenuButtonUI.createUI(jButton6));
        jButton7.setUI((BasicButtonUI)MyBasicMenuButtonUI.createUI(jButton7));
        jButton8.setUI((BasicButtonUI)MyBasicMenuButtonUI.createUI(jButton8));
        jButton9.setUI((BasicButtonUI)MyBasicMenuButtonUI.createUI(jButton9));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
