/**
 * Copyright (c) 2010-2015 Bryan Beck.
 * All rights reserved.
 * 
 * This project is licensed under LGPL v2.1.
 * See jMovieManager-license.txt for details.
 * 
 */
package jMovieManager.swing.gui;

import jMovieManager.swing.gui.components.MyJFileChooser;
import jMovieManager.swing.gui.other.JMMFileFilter.FilterType;
import jmm.utils.Settings;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jmm.persist.PersistingManager;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

/**
 * Creates a GUI to save your database
 *
* @author Bryan Beck
 * @since 20.10.2010
 */
public class SaveDialogGUI extends javax.swing.JDialog{
    /** Logger. */
    private static final Logger LOG = LoggerFactory.logger(SaveDialogGUI.class);
    
    private ResourceBundle bundle;  
   
    /** 
     * Creates new SaveDialogGUI to save a database file
     * 
     * @see JDialog#JDialog(java.awt.Frame, boolean) 
     **/
    public SaveDialogGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        bundle = ResourceBundle.getBundle("jMovieManager.swing.resources.MovieManager");
        
        initComponents();
        //GUI zentriert darstellen
        this.setLocationRelativeTo(parent);
        
        //Füge eigene Methode bei Fensterschließen hinzu
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                status = CANCEL_OPTION;
                dispose();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jMovieManager/swing/resources/MovieManager"); // NOI18N
        setTitle(bundle.getString("SaveDialogGUI.headline")); // NOI18N
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("SaveDialogGUI.jLabel1")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 88));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 86));

        jButton1.setText(bundle.getString("SaveDialogGUI.jButton1")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(90, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText(bundle.getString("SaveDialogGUI.jButton2")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(90, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(90, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText(bundle.getString("SaveDialogGUI.jButton3")); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(90, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(90, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * jButton1 - Yes <br/>
     * Setzt den Status auf ja und initialisiert den Auswahldialog
     * Wird beim betätigen des "Ja" Buttons ausgeführt
     *
     * @param evt Event, welches durch den Button Klick ausgelöst wurde
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            //Wenn kein Speicherpfad gesetzt, dann zeige jFileChooser an
            if(Settings.getInstance().getHsqlDbPath().isEmpty()){
                String savePath = this.initFileChooser();
                if(!savePath.isEmpty()){
                    PersistingManager.INSTANCE.changeDBPath(savePath, PersistingManager.Process.SAVE);           
                    jButton1ActionPerformed(evt);
                }
            }else{                
                status = APPROVE_OPTION;
            }
            //Fenster schließen
           this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Setzt den Status auf Nein
     * Wird beim betätigen des "Nein" Buttons ausgeführt
     *
     * @param evt Event, welches durch den Button Klick ausgelöst wurde
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        status = DECLINE_OPTION;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Setzt den Status aus Abbruch
     * Wird beim betätigen des "Abbrechen" Buttons ausgeführt
     *
     * @param evt Event, welches durch den Button Klick ausgelöst wurde
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        status = CANCEL_OPTION;
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * Macht die GUI sichtbar
     *
     * @return status - Der Dialog, der ausgewählt wurde
     */
    public int showDialog(){
        this.setVisible(true);
        //Wird erst nach dem dispose(); ausgeführt
        return status;
    }

    /**
     * Create a file choose dialog to select the filepath
     */
    public String initFileChooser(){
        MyJFileChooser jFileChooser1 = new MyJFileChooser(Settings.getInstance().getHsqlDbPath(), FilterType.DB);  
        //Setzte Speicherdialog
        jFileChooser1.setDialogType(JFileChooser.SAVE_DIALOG);
                
        //wenn "speichern" geklickt wurde
        do{
            if(jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
                localSavePath = jFileChooser1.getSelectedFile().toString();
                if(localSavePath.endsWith(".script")){
                    localSavePath = localSavePath.substring(0, localSavePath.length()-7);
                }

                //Überprüfe ob Datei schon existiert
                if(jFileChooser1.getSelectedFile().exists()){
                    int choice = javax.swing.JOptionPane.showOptionDialog(this,
                            jFileChooser1.getSelectedFile().getName()+ " " + bundle.getString("SaveDialogGUI.file.exist"),
                            bundle.getString("SaveDialogGUI.file.exist.headline"),
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.WARNING_MESSAGE,
                            null, null, null);
                    //0 == Yes, 1 == No, -1 == Cancel
                    if(choice == 0){
                        dispose();
                        return localSavePath;
                    }
                }else{
                    dispose();
                    return localSavePath;
                }
            }else{
                dispose();
                return "";
            }
        }while(jFileChooser1.getSelectedFile().exists());
        return localSavePath;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public final static int APPROVE_OPTION = 1;
    public final static int DECLINE_OPTION = 2;
    public final static int CANCEL_OPTION = 0;
    private int status;
    private String localSavePath;
}
