/**
 * Copyright (c) 2010-2015 Bryan Beck.
 * All rights reserved.
 * 
 * This project is licensed under LGPL v2.1.
 * See jMovieManager-license.txt for details.
 * 
 */
package jMovieManager.swing.gui.splitpane.right;

import jMovieManager.swing.gui.ColorInterface;
import java.awt.Cursor;
import java.awt.Dimension;
import java.io.File;
import java.util.Iterator;
import java.util.Locale;
import java.util.Observable;
import java.util.Observer;
import java.util.ResourceBundle;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import jmm.data.Actor;
import jmm.data.LocalVideoFile;
import jmm.data.VideoFile.FSK;
import jMovieManager.swing.gui.UIInterface;
import jMovieManager.swing.gui.components.MyOverlapJLabel;
import jMovieManager.swing.gui.components.ui.MyBasicScrollBarUI;
import jMovieManager.swing.gui.font.JMMFont;
import static jMovieManager.swing.gui.font.JMMFont.labelFont;
import jMovieManager.swing.gui.other.MyIconFactory;
import jMovieManager.swing.gui.splitpane.left.MovieTabGUI;
import java.util.Map;
import jmm.utils.LocaleManager;
import jmm.utils.PictureManager;
import jmm.utils.Settings;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

/**
 * AbstractDetailGUI.java
 *
 * @author Bryan Beck
 * @since 21.11.2010
 */
public abstract class AbstractDetailGUI extends javax.swing.JFrame implements UIInterface, Observer{
    /** Logger. */
    private static final Logger LOG = LoggerFactory.logger(AbstractDetailGUI.class);
    
    protected ResourceBundle bundle;
    protected ResourceBundle genreKeyAndCodecBundle;
    private LocalVideoFile videoFile;
    
//    private Thread pictureThread;
        
    /** Creates new form AbstractDetailGUI */
    protected AbstractDetailGUI() {
        bundle = ResourceBundle.getBundle("jMovieManager.swing.resources.MovieManager");
        genreKeyAndCodecBundle = LocaleManager.getInstance().getGenreKeyAndCodecBundle();
        initComponents();
        
        //Fuer Linux
        jScrollPane1.setViewportBorder(null);
        
        //pictureThread = new Thread();
        //Neues Attributset
        SimpleAttributeSet as = new SimpleAttributeSet();
        //Füge dem AttributSet, Blocksatz hinzu
        StyleConstants.setAlignment( as, StyleConstants.ALIGN_JUSTIFIED );
        StyleConstants.setFontSize(as, 14);
        StyleConstants.setFontFamily(as, "Tahoma");
        StyleConstants.setForeground(as, UIManager.getColor("TextPane.foreground"));
        //Neues StyleDokument
        StyledDocument doc = jTextPane1.getStyledDocument();
        Style style = doc.addStyle( "ALIGN_JUSTIFIED", null );
        style.addAttributes( as );
        doc.setLogicalStyle( 0, style );   
        jTextPane1.setFont(JMMFont.largeIOFont);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new MyOverlapJLabel();
        jPanel10 = new javax.swing.JPanel();
        detailsPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 200), new java.awt.Dimension(5, 250), new java.awt.Dimension(5, 250));
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel22 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        ratingPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 30), new java.awt.Dimension(5, 50), new java.awt.Dimension(5, 50));
        jPanel7 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        buttonPanel = new javax.swing.JPanel();

        caPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 10));
        caPanel.setMinimumSize(new java.awt.Dimension(760, 60));
        caPanel.setPreferredSize(new java.awt.Dimension(760, 60));
        caPanel.setLayout(new javax.swing.BoxLayout(caPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Custom Attributes"));
        jPanel1.setMinimumSize(new java.awt.Dimension(740, 47));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 47));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 3));

        jPanel20.setMaximumSize(new java.awt.Dimension(356, 18));
        jPanel20.setMinimumSize(new java.awt.Dimension(356, 18));
        jPanel20.setPreferredSize(new java.awt.Dimension(356, 18));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setText("CustomAttribute:");
        jLabel66.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel66.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel66.setPreferredSize(new java.awt.Dimension(150, 18));
        jPanel20.add(jLabel66);

        jLabel67.setText("CustomAttributeValue");
        jLabel67.setMaximumSize(new java.awt.Dimension(206, 18));
        jLabel67.setMinimumSize(new java.awt.Dimension(206, 18));
        jLabel67.setPreferredSize(new java.awt.Dimension(206, 18));
        jPanel20.add(jLabel67);

        jPanel1.add(jPanel20);

        jPanel21.setMaximumSize(new java.awt.Dimension(356, 18));
        jPanel21.setMinimumSize(new java.awt.Dimension(356, 18));
        jPanel21.setPreferredSize(new java.awt.Dimension(356, 18));
        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.LINE_AXIS));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setText("CustomAttribute:");
        jLabel68.setMaximumSize(new java.awt.Dimension(150, 18));
        jLabel68.setMinimumSize(new java.awt.Dimension(150, 18));
        jLabel68.setPreferredSize(new java.awt.Dimension(150, 18));
        jPanel21.add(jLabel68);

        jLabel69.setText("CustomAttributeValue");
        jLabel69.setMaximumSize(new java.awt.Dimension(206, 18));
        jLabel69.setMinimumSize(new java.awt.Dimension(206, 18));
        jLabel69.setPreferredSize(new java.awt.Dimension(206, 18));
        jPanel21.add(jLabel69);

        jPanel1.add(jPanel21);

        caPanel.add(jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jMovieManager/swing/resources/MovieManager"); // NOI18N
        setTitle(bundle.getString("AboutGUI.headline")); // NOI18N

        jScrollPane2.setBorder(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(760, 700));

        jPanel2.setFont(new java.awt.Font("Serif", 0, 11)); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 690));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 690));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel14.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel14.setMinimumSize(new java.awt.Dimension(750, 40));
        jPanel14.setPreferredSize(new java.awt.Dimension(750, 40));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.Y_AXIS));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(ColorInterface.titledBorderForeground);
        jLabel30.setAlignmentX(0.5F);
        jLabel30.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 3, 0));
        jLabel30.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel30.setMinimumSize(new java.awt.Dimension(760, 25));
        jLabel30.setPreferredSize(new java.awt.Dimension(760, 25));
        jPanel14.add(jLabel30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel34.setAlignmentX(0.5F);
        jLabel34.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jLabel34.setMaximumSize(new java.awt.Dimension(32767, 15));
        jLabel34.setMinimumSize(new java.awt.Dimension(760, 15));
        jLabel34.setPreferredSize(new java.awt.Dimension(760, 15));
        jPanel14.add(jLabel34);

        jPanel2.add(jPanel14);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 420));
        jPanel8.setMinimumSize(new java.awt.Dimension(750, 425));
        jPanel8.setPreferredSize(new java.awt.Dimension(750, 425));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(290, 420));
        jPanel9.setMinimumSize(new java.awt.Dimension(290, 420));
        jPanel9.setPreferredSize(new java.awt.Dimension(290, 420));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 7));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(bundle.getString("AbstractDetailGUI.jLabel10")); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(270, 405));
        jLabel10.setMinimumSize(new java.awt.Dimension(270, 405));
        jLabel10.setPreferredSize(new java.awt.Dimension(270, 405));
        jPanel9.add(jLabel10);

        jPanel8.add(jPanel9);

        jPanel10.setMinimumSize(new java.awt.Dimension(460, 420));
        jPanel10.setPreferredSize(new java.awt.Dimension(460, 420));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.PAGE_AXIS));

        detailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), bundle.getString("AbstractDetailGUI.detailsPanel"))); // NOI18N
        detailsPanel.setMaximumSize(new java.awt.Dimension(32779, 210));
        detailsPanel.setMinimumSize(new java.awt.Dimension(460, 210));
        detailsPanel.setPreferredSize(new java.awt.Dimension(460, 210));
        detailsPanel.setLayout(new javax.swing.BoxLayout(detailsPanel, javax.swing.BoxLayout.LINE_AXIS));
        detailsPanel.add(filler2);

        jPanel5.setMinimumSize(new java.awt.Dimension(465, 225));
        jPanel5.setPreferredSize(new java.awt.Dimension(435, 225));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel4.setPreferredSize(new java.awt.Dimension(470, 25));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jPanel23.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel23.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel23.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.LINE_AXIS));

        jLabel37.setFont(JMMFont.labelFont);
        jLabel37.setText(bundle.getString("AbstractDetailGUI.jLabel37")); // NOI18N
        jLabel37.setMaximumSize(new java.awt.Dimension(115, 25));
        jLabel37.setMinimumSize(new java.awt.Dimension(115, 25));
        jLabel37.setPreferredSize(new java.awt.Dimension(115, 25));
        jPanel23.add(jLabel37);

        jLabel38.setFont(JMMFont.smallIOFont);
        jLabel38.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel38.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel38.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel23.add(jLabel38);

        jPanel4.add(jPanel23);

        jPanel24.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel24.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel24.setPreferredSize(new java.awt.Dimension(230, 25));
        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(jPanel24);

        jPanel5.add(jPanel4);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel6.setMinimumSize(new java.awt.Dimension(470, 25));
        jPanel6.setPreferredSize(new java.awt.Dimension(470, 25));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel41.setFont(JMMFont.labelFont);
        jLabel41.setText(bundle.getString("AbstractDetailGUI.jLabel41")); // NOI18N
        jLabel41.setMaximumSize(new java.awt.Dimension(115, 25));
        jLabel41.setMinimumSize(new java.awt.Dimension(115, 25));
        jLabel41.setPreferredSize(new java.awt.Dimension(115, 25));
        jPanel6.add(jLabel41);

        jLabel42.setFont(JMMFont.smallIOFont);
        jLabel42.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel42.setMinimumSize(new java.awt.Dimension(350, 25));
        jLabel42.setPreferredSize(new java.awt.Dimension(350, 25));
        jPanel6.add(jLabel42);

        jPanel5.add(jPanel6);

        jPanel17.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel17.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel17.setPreferredSize(new java.awt.Dimension(470, 25));
        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel12.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel61.setFont(JMMFont.labelFont);
        jLabel61.setText(bundle.getString("AbstractDetailGUI.jLabel61")); // NOI18N
        jLabel61.setMaximumSize(new java.awt.Dimension(115, 25));
        jLabel61.setMinimumSize(new java.awt.Dimension(115, 25));
        jLabel61.setPreferredSize(new java.awt.Dimension(115, 25));
        jPanel12.add(jLabel61);

        jLabel62.setFont(JMMFont.smallIOFont);
        jLabel62.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel62.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel62.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel12.add(jLabel62);

        jPanel17.add(jPanel12);

        jPanel13.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel13.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel63.setFont(JMMFont.labelFont);
        jLabel63.setText(bundle.getString("AbstractDetailGUI.jLabel63")); // NOI18N
        jLabel63.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel63.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel63.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanel13.add(jLabel63);

        jLabel64.setFont(JMMFont.smallIOFont);
        jLabel64.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel64.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel64.setName(""); // NOI18N
        jLabel64.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel13.add(jLabel64);

        jPanel17.add(jPanel13);

        jPanel5.add(jPanel17);

        jPanel18.setMaximumSize(new java.awt.Dimension(32767, 95));
        jPanel18.setMinimumSize(new java.awt.Dimension(0, 95));
        jPanel18.setPreferredSize(new java.awt.Dimension(470, 95));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jLabel65.setFont(JMMFont.labelFont);
        jLabel65.setText(bundle.getString("AbstractDetailGUI.jLabel65")); // NOI18N
        jLabel65.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel65.setMaximumSize(new java.awt.Dimension(115, 95));
        jLabel65.setMinimumSize(new java.awt.Dimension(115, 95));
        jLabel65.setPreferredSize(new java.awt.Dimension(115, 95));
        jPanel18.add(jLabel65);

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 95));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 95));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(340, 95));

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane2.setBorder(null);
        jTextPane2.setFont(JMMFont.smallIOFont);
        jTextPane2.setMaximumSize(new java.awt.Dimension(32767, 95));
        jTextPane2.setMinimumSize(new java.awt.Dimension(0, 95));
        jTextPane2.setPreferredSize(new java.awt.Dimension(340, 95));
        jScrollPane1.setViewportView(jTextPane2);

        jPanel18.add(jScrollPane1);

        jPanel5.add(jPanel18);

        detailsPanel.add(jPanel5);

        jPanel10.add(detailsPanel);

        jPanel22.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel22.setMinimumSize(new java.awt.Dimension(460, 10));
        jPanel22.setPreferredSize(new java.awt.Dimension(460, 10));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel22);

        jPanel35.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel35.setMinimumSize(new java.awt.Dimension(460, 10));
        jPanel35.setPreferredSize(new java.awt.Dimension(460, 10));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel35);

        ratingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), bundle.getString("AbstractDetailGUI.ratingPanel"))); // NOI18N
        ratingPanel.setMaximumSize(new java.awt.Dimension(32767, 50));
        ratingPanel.setMinimumSize(new java.awt.Dimension(460, 50));
        ratingPanel.setPreferredSize(new java.awt.Dimension(460, 50));
        ratingPanel.setLayout(new javax.swing.BoxLayout(ratingPanel, javax.swing.BoxLayout.LINE_AXIS));
        ratingPanel.add(filler1);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jPanel25.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel25.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25, javax.swing.BoxLayout.LINE_AXIS));

        jLabel77.setFont(JMMFont.labelFont);
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel77.setText(bundle.getString("AbstractDetailGUI.jLabel77")); // NOI18N
        jLabel77.setMaximumSize(new java.awt.Dimension(115, 25));
        jLabel77.setMinimumSize(new java.awt.Dimension(115, 25));
        jLabel77.setPreferredSize(new java.awt.Dimension(115, 25));
        jPanel25.add(jLabel77);

        jLabel78.setFont(JMMFont.smallIOFont);
        jLabel78.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel78.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel78.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel25.add(jLabel78);

        jPanel7.add(jPanel25);

        jPanel26.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel26.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.LINE_AXIS));

        jLabel79.setFont(JMMFont.labelFont);
        jLabel79.setText(bundle.getString("AbstractDetailGUI.jLabel79")); // NOI18N
        jLabel79.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel79.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel79.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanel26.add(jLabel79);

        jLabel80.setFont(JMMFont.smallIOFont);
        jLabel80.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel80.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel80.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel26.add(jLabel80);

        jPanel7.add(jPanel26);

        ratingPanel.add(jPanel7);

        jPanel10.add(ratingPanel);

        jPanel8.add(jPanel10);

        jPanel19.setMaximumSize(new java.awt.Dimension(10, 420));
        jPanel19.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel19.setName(""); // NOI18N
        jPanel19.setPreferredSize(new java.awt.Dimension(10, 420));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel19);

        jPanel2.add(jPanel8);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 10));
        jPanel11.setAlignmentX(0.5F);
        jPanel11.setMinimumSize(new java.awt.Dimension(0, 100));
        jPanel11.setPreferredSize(new java.awt.Dimension(750, 225));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.PAGE_AXIS));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), bundle.getString("AbstractDetailGUI.jScrollPane3"))); // NOI18N
        jScrollPane3.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(740, 210));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(240, 240, 240));
        jTextPane1.setFont(JMMFont.largeIOFont);
        jTextPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextPane1.setPreferredSize(new java.awt.Dimension(740, 210));
        jScrollPane3.setViewportView(jTextPane1);

        jPanel11.add(jScrollPane3);

        jPanel2.add(jPanel11);

        buttonPanel.setMinimumSize(new java.awt.Dimension(0, 42));
        buttonPanel.setPreferredSize(new java.awt.Dimension(740, 42));
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));
        jPanel2.add(buttonPanel);

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    * Gibt das RootPanel zurück, auf dem alle Komponenten sind
    *
    * @return JPanel Das Rootpanel
    */
    public JScrollPane getRootPanel(){
        return jScrollPane2;
    }
    
    /**
    * Gibt das rechte Panel zurück
    *
    * @return JPanel Das rechte Panel
    */    
    public JPanel getRightPanel(){
        return jPanel10;
    }

//    /**
//     * @return the pictureThread
//     */
//    public Thread getPictureThread() {
//        return pictureThread;
//    }
    
    /**
    * Observer method for locale update <br/>
    * Updates all localized GUI elements
    * 
    * @param o the observerable object
    * @param arg the updated locale
    */
   @Override
    public void update(Observable o, Object arg) {
       if(arg instanceof Locale){
           updateGUILocalization();
       }
    }

   /**
   * Aktualisiert alle Labels, Buttons, Tooltips und sonstigen Texte der GUI
   * auf das gesetzte Locale
   */
   protected void updateGUILocalization(){
       bundle = ResourceBundle.getBundle("jMovieManager.swing.resources.MovieManager");
       genreKeyAndCodecBundle = LocaleManager.getInstance().getGenreKeyAndCodecBundle();

       if(jLabel10.getIcon() == null){
           jLabel10.setText(bundle.getString("AbstractDetailGUI.jLabel10"));
       }
       jLabel37.setText(bundle.getString("AbstractDetailGUI.jLabel37"));
       jLabel41.setText(bundle.getString("AbstractDetailGUI.jLabel41"));

       jLabel61.setText(bundle.getString("AbstractDetailGUI.jLabel61"));
       jLabel63.setText(bundle.getString("AbstractDetailGUI.jLabel63"));
       jLabel65.setText(bundle.getString("AbstractDetailGUI.jLabel65"));
       jLabel77.setText(bundle.getString("AbstractDetailGUI.jLabel77"));
       jLabel79.setText(bundle.getString("AbstractDetailGUI.jLabel79"));
       
       //Titled Borders
       ((TitledBorder)detailsPanel.getBorder()).setTitle(bundle.getString("AbstractDetailGUI.detailsPanel"));
       ((TitledBorder)ratingPanel.getBorder()).setTitle(bundle.getString("AbstractDetailGUI.ratingPanel"));
       ((TitledBorder)jScrollPane3.getBorder()).setTitle(bundle.getString("AbstractDetailGUI.jScrollPane3"));
       //Repaint scrollpAne because of an updated title
       jScrollPane3.repaint();
       //Genres
       if(videoFile != null){
            this.updateGenres(videoFile);
           //Play & Trailer Button
           int compontents = buttonPanel.getComponentCount(); 
           for(int i = 0; i < compontents; i ++){
               if(i == 0){                      //Trailer Button             
                   ((JButton)buttonPanel.getComponent(i)).setText(bundle.getString("AbstractDetailGUI.trailerButton"));
               }  
               else if(compontents > 2){        //Play Button Teil x
                   ((JButton)buttonPanel.getComponent(i)).setText(bundle.getString("AbstractDetailGUI.playButton.part") + ' ' +  (i));
               }else{                           //Play Button
                   ((JButton)buttonPanel.getComponent(i)).setText(bundle.getString("AbstractDetailGUI.playButton"));
               }
           }
       }
   }

    /**
    * Aktualisiert das jPanel 2 mit
    * Informationen des Movie Objekts<br/><br/>
    * <b>this.pack() muss ausgeführt werden</b> , damit die Panel Komponenten korrekt dargestellt werden
    *
    * @param localVideoFile Das Video Objekt
    */
    protected void updateVideoDetail(final LocalVideoFile localVideoFile){
//        if(pictureThread != null && pictureThread.isAlive()){
//            pictureThread.interrupt();               
//        }           
        this.videoFile = localVideoFile;

        buttonPanel.removeAll();

        jLabel10.setIcon(null);
        ((MyOverlapJLabel)jLabel10).setWatermark(null);
        jLabel10.setText(bundle.getString("AbstractDetailGUI.jLabel10.picLoad"));
        
        //Titel
        if(!localVideoFile.getTitle().isEmpty()){
            jLabel30.setText(localVideoFile.getTitle());
        }else{
            jLabel30.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
        }
        //Originaltitel
        if(!localVideoFile.getOriginalTitle().isEmpty()){
            if(jPanel14.getComponentCount() == 1){
                jPanel14.add(jLabel34);
                jPanel14.setPreferredSize(new Dimension(jPanel14.getWidth(), 40));
            }
            jLabel34.setText(localVideoFile.getOriginalTitle());
        }else{
            if(jPanel14.getComponentCount() == 2){
                jPanel14.remove(jLabel34);
                jPanel14.setPreferredSize(new Dimension(jPanel14.getWidth(), 25));
            }
        }
        //Playtime
        if(localVideoFile.getPlaytime() == 0){
            jLabel38.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
        }else{
            jLabel38.setText(Integer.toString(localVideoFile.getPlaytime()) + ' ' + bundle.getString("AbstractDetailGUI.jLabel38"));
        }  
        //FSK
        if(Settings.getInstance().isOverlapFSKImage()){
            FSK fsk = localVideoFile.getFsk();
            if(fsk == FSK.FSK_0){
                ((MyOverlapJLabel)jLabel10).setWatermark(MyIconFactory.FSK_0);
            }
            else if(fsk == FSK.FSK_6){
                ((MyOverlapJLabel)jLabel10).setWatermark(MyIconFactory.FSK_6);
            }
            else if(fsk == FSK.FSK_12){
                ((MyOverlapJLabel)jLabel10).setWatermark(MyIconFactory.FSK_12);
            }
            else if(fsk == FSK.FSK_16){
                ((MyOverlapJLabel)jLabel10).setWatermark(MyIconFactory.FSK_16);
            }
            else if(fsk == FSK.FSK_18){
                ((MyOverlapJLabel)jLabel10).setWatermark(MyIconFactory.FSK_18);
            }        
        }
        
        //Genres
        this.updateGenres(localVideoFile);

        //ReleaseYear
        if(localVideoFile.getReleaseYear() != 0){
            //jLabel70.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
            jLabel30.setText(jLabel30.getText() + " (" + localVideoFile.getReleaseYear() + ")");
       //     jLabel70.setText(Integer.toString(localVideoFile.getReleaseYear()));
        }
        //Publisher
        if(!localVideoFile.getPublisher().isEmpty()){
            jLabel62.setText(localVideoFile.getPublisher());
        }else{
            jLabel62.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
        }
        //Regisseur
        if(!localVideoFile.getDirector().isEmpty()){
            jLabel64.setText(localVideoFile.getDirector());
        }else{
            jLabel64.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
        }
        //Schauspieler
        if(!localVideoFile.getActors().isEmpty()){
            StringBuilder sb = new StringBuilder();
            
            Iterator<Actor> actors = localVideoFile.getActors().iterator();
            Actor actor = actors.next();
            while(actors.hasNext()){
                sb.append(actor.getName()).append(", ");
                actor = actors.next();
            }
            //Der letzte Actor
            sb.append(actor.getName());
            jTextPane2.setText(sb.toString());
        }else{
            jTextPane2.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
        }
        jTextPane2.select(0, 0);

        //IMDB Rating
        if(localVideoFile.getOnlineRating() == 0){
            jLabel78.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
        }else{
            jLabel78.setText(Double.toString(localVideoFile.getOnlineRating()) + bundle.getString("AbstractDetailGUI.jLabel78"));
        }
        //Personal Rating
        if(localVideoFile.getPersonalRating() == 0){
            jLabel80.setText(bundle.getString("AbstractDetailGUI.jLabelEmpty"));
        }else{
            jLabel80.setText(Double.toString(localVideoFile.getPersonalRating()) + bundle.getString("AbstractDetailGUI.jLabel80"));
        }        
        
        //Custom attributes
        Map<String, String> customAttributes = videoFile.getCustomAttributes();
        if(!customAttributes.isEmpty()){
            if(jPanel2.getComponentCount() == 4){
                jPanel2.add(caPanel, 2);
            }
            jPanel1.removeAll();
            double counter = customAttributes.size();
            int labelHeight = 18;
            for(String key: customAttributes.keySet()){
                String value = customAttributes.get(key);
                JPanel panel = new JPanel();
                panel.setPreferredSize(new Dimension(356, labelHeight));
                panel.setMaximumSize(new Dimension(356, labelHeight));
                panel.setMinimumSize(new Dimension(356, labelHeight));
                panel.setLayout(new BoxLayout(panel, BoxLayout.LINE_AXIS));
                JLabel keyLabel = new JLabel(key + ":");
                keyLabel.setFont(labelFont);
                keyLabel.setPreferredSize(new Dimension(150, labelHeight));
                keyLabel.setMaximumSize(new Dimension(150, labelHeight));
                keyLabel.setMinimumSize(new Dimension(150, labelHeight));
                JLabel valueLabel = new JLabel(value);
                valueLabel.setFont(JMMFont.smallIOFont);
                valueLabel.setPreferredSize(new Dimension(206, labelHeight));
                valueLabel.setMaximumSize(new Dimension(206, labelHeight));
                valueLabel.setMinimumSize(new Dimension(206, labelHeight));
                panel.add(keyLabel);
                panel.add(valueLabel);
                jPanel1.add(panel);
            }
            //restore default height
            if(additioalHeight > -1){
                jPanel2.setPreferredSize(new Dimension(jPanel2.getPreferredSize().width, jPanel2.getPreferredSize().height-additioalHeight));
            }         
            //layout panels //32 // 47
            //include 3 vertical gap from flow layout
            double rowCounter = (counter/2) + 0.5;
            int height = 36 + ((labelHeight+3) * (int)rowCounter);
            height += 3;
            additioalHeight = height;
            caPanel.setPreferredSize(new Dimension(caPanel.getPreferredSize().width, additioalHeight));
            caPanel.setMinimumSize(new Dimension(caPanel.getMinimumSize().width, additioalHeight));
            jPanel2.setPreferredSize(new Dimension(jPanel2.getPreferredSize().width, jPanel2.getPreferredSize().height+additioalHeight));
        }else{
            if(jPanel2.getComponentCount() == 5){
                jPanel2.remove(caPanel);
                //restore default height
                if(additioalHeight > -1){
                    jPanel2.setPreferredSize(new Dimension(jPanel2.getPreferredSize().width, jPanel2.getPreferredSize().height-additioalHeight));
                }
                additioalHeight = -1;
            }
        }
        
        //Beschreibung
        jTextPane1.setText(localVideoFile.getDescription());
        jTextPane1.select(0, 0);
        //Bild      
        //Check and open image from the fileName path;
        String fileName = String.valueOf(PictureManager.getHash(videoFile));
        String dirPath = Settings.getInstance().getHsqlDbPath() + ".pics";
        File picture = new File(dirPath, fileName + ".jpg");
        if(picture.exists() && picture.isFile()){
            //set picture as image
            ImageIcon source = new ImageIcon(picture.getAbsolutePath());
            localVideoFile.setImage(source);
        }
        if(null != localVideoFile.getImage() || (!localVideoFile.getImagePath().isEmpty())){ 
            jLabel10.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            Thread pictureThreadd = new Thread(new Runnable() {
                @Override
                 public void run() {
                    ImageIcon scaledIcon;
                     if(null != localVideoFile.getImage()){
                         scaledIcon = localVideoFile.getImage();
                     }
                     else{
                         scaledIcon = PictureManager.getScaledImage(localVideoFile.getImagePath(), PictureManager.picture_width,PictureManager.picture_height);
                     }
//                     if(videoFile == localVideoFile){
//                     if(!pictureThread.isInterrupted()){                  
                        if(null != scaledIcon){
                            //Setzte beim ersten Laden die Referenz zum objekt
                            if(null == localVideoFile.getImage()){
                                localVideoFile.setImage(scaledIcon);
                            }
                            jLabel10.setText("");
                            jLabel10.setIcon(scaledIcon);
                        }else{
                            jLabel10.setIcon(null);
                            jLabel10.setText(bundle.getString("AbstractDetailGUI.error.noPic"));
                        }
//                     }                    
                     jLabel10.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                }
            });
            pictureThreadd.start();
//            getPictureThread().start();
        }else{
            jLabel10.setIcon(null);
            jLabel10.setText(bundle.getString("AbstractDetailGUI.error.noPic"));
        }
    }
    //additional height for custom attributes panel
    private int additioalHeight = -1;
    
    /**
     * Aktualisiert die Genres auf der GUI
     * 
     * @param videoFile Das Objekt, dessen Genres aktualisiert werden sollen 
     */
    private void updateGenres(LocalVideoFile videoFile){
        if(!videoFile.getGenreKeys().isEmpty()){
            Iterator<String> genreKeys = videoFile.getGenreKeys().iterator();
            String genreKey = genreKeys.next();
            
            StringBuilder sb = new StringBuilder();
            while(genreKeys.hasNext()){
                if(genreKeyAndCodecBundle.containsKey(genreKey)){
                    sb.append(genreKeyAndCodecBundle.getString(genreKey)).append(", ");
                }
                else{
                    sb.append(genreKey).append(", ");
                }
                genreKey = genreKeys.next();
            }
            //Das letzte Genre
            if(genreKeyAndCodecBundle.containsKey(genreKey)){
                sb.append(genreKeyAndCodecBundle.getString(genreKey));
            }            
            else{
                sb.append(genreKey);
            }
            jLabel42.setText(sb.toString());
        }else{
            jLabel42.setText(genreKeyAndCodecBundle.getString("Value.empty"));
        }        
    }
    
   /**
    * Methode zum Anpassen der GUI an das neue Look and Feel
    **/
    @Override
   public void changeUI(){
        SwingUtilities.invokeLater(new Runnable() {   //InvokeAndWait, damit es bei Kindklassen keine Thread Probleme beim initialisieren gibt
             @Override
             public void run() {
                //Notwendig für Windows XP und Linux
                jTextPane1.setBackground(UIManager.getColor("TextPane.background"));
                jTextPane2.setBackground(UIManager.getColor("TextPane.background"));

                jScrollPane1.getHorizontalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jTextPane2)); 
                jScrollPane1.getVerticalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jTextPane2));   

                jScrollPane3.getHorizontalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jTextPane1));  
                jScrollPane3.getVerticalScrollBar().setUI((MyBasicScrollBarUI)MyBasicScrollBarUI.createUI(jTextPane1));   
             }
         });
   }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel buttonPanel;
    protected javax.swing.JPanel caPanel;
    protected javax.swing.JPanel detailsPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    protected javax.swing.JPanel ratingPanel;
    // End of variables declaration//GEN-END:variables
}
