/**
 * Copyright (c) 2010-2015 Bryan Beck.
 * All rights reserved.
 * 
 * This project is licensed under LGPL v2.1.
 * See jMovieManager-license.txt for details.
 * 
 */
package jMovieManager.swing.gui.splitpane.right;

import jmm.utils.OperatingSystem;
import java.awt.Cursor;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.JButton;
import javax.swing.border.TitledBorder;
import jmm.data.Season;
import jmm.data.Serie;
import jmm.utils.LocaleManager;
import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;

/**
 *
 * @author Bryan Beck
 * @since 26.10.2011
 * 
 */
public class SerieDetailGUI extends AbstractDetailGUI {
    /** Logger. */
    private static final Logger LOG = LoggerFactory.logger(SerieDetailGUI.class);
    
    private static SerieDetailGUI instance;

    /** Creates new form SerieDetailGUI */
    public SerieDetailGUI() {
        super();
        initComponents();
        super.getRightPanel().add(jPanel21, 2);
        
        if(useCustomLAF){
            this.changeUI();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jMovieManager/swing/resources/MovieManager"); // NOI18N
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), bundle.getString("SerieDetailGUI.jPanel21"))); // NOI18N
        jPanel21.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel21.setMinimumSize(new java.awt.Dimension(460, 50));
        jPanel21.setPreferredSize(new java.awt.Dimension(460, 50));
        jPanel21.setLayout(new java.awt.GridLayout(1, 2));

        jPanel25.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel25.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25, javax.swing.BoxLayout.LINE_AXIS));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel77.setText(bundle.getString("SerieDetailGUI.jLabel77")); // NOI18N
        jLabel77.setMaximumSize(new java.awt.Dimension(120, 25));
        jLabel77.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel77.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel25.add(jLabel77);

        jLabel78.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel78.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel78.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel25.add(jLabel78);

        jPanel21.add(jPanel25);

        jPanel26.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel26.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.LINE_AXIS));

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel79.setText(bundle.getString("SerieDetailGUI.jLabel79")); // NOI18N
        jLabel79.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel79.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel79.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanel26.add(jLabel79);

        jLabel80.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel80.setMinimumSize(new java.awt.Dimension(120, 25));
        jLabel80.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel26.add(jLabel80);

        jPanel21.add(jPanel26);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Singleton Konstruktor der Klasse SerieDetailGUI
    *
    * @return instance Die Instanz der Klasse
    */
    public static SerieDetailGUI getInstance(){
        if(instance == null){
            instance = new SerieDetailGUI();
            LocaleManager.getInstance().addObserver(instance);
        }
        return instance;
    }     
        
   /**
   * Aktualisiert alle Labels, Buttons, Tooltips und sonstigen Texte der GUI
   * auf das gesetzte Locale
   */
   @Override
   protected void updateGUILocalization(){
       super.updateGUILocalization();
       ((TitledBorder)jPanel21.getBorder()).setTitle(bundle.getString("SerieDetailGUI.jPanel21"));
       
       jLabel77.setText(bundle.getString("SerieDetailGUI.jLabel77"));
       jLabel79.setText(bundle.getString("SerieDetailGUI.jLabel79"));
   }

    /**
    * Aktualisiert die Panel Daten mit
    * Informationen des Serie Objekts
    *
    * @param serie Das Serie Objekt
    */
    public void updateSerieDetail(final Serie serie){ 
        super.updateVideoDetail(serie);
       
        //Seasons
        jLabel78.setText(String.valueOf(serie.getSeasons().size()));
        //Episodes
        int episodeCounter = 0;
        for(Season season: serie.getSeasons()){
            episodeCounter += season.getEpisodes().size();
        }
        jLabel80.setText(String.valueOf(episodeCounter));
        
        //Erstelle Trailer Button
        JButton trailerButton = new JButton(bundle.getString("AbstractDetailGUI.trailerButton"));
        trailerButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        trailerButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    String title = serie.getTitle();
                    String searchURL = "http://www.youtube.com/results?search_query=" + title.replace(' ', '+'); // + "&hd=1";  //"fmt=22";
               
                    try {
                        //Öffne den Standardbrowser
                        OperatingSystem.openBrowser(searchURL); 
                    } catch (IOException | URISyntaxException ex) {
                        LOG.error("URL: " + searchURL + " could not be opened in the browser.", ex);
                    }
            }
        });
        buttonPanel.add(trailerButton);        
        
        this.pack();    //required for dynamic buttons
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    // End of variables declaration//GEN-END:variables
}
